<?php
$servername = "localhost";
$username = "mcabrera2";
$password = "2478*";
$dbname = "apialdeas";
/*
$servername = "localhost";
$username = "aisosmx_rebelbot";
$password = "Rebelware10*";
$dbname = "aisosmx_apialdeas";*/


// Create connection
$conn = new mysqli($servername, $username, $password, $dbname);
// Check connection
if ($conn->connect_error) {
  die(" fallo la conexion: " . $conn->connect_error);
}

// sql to create table
$sql = "INSERT INTO `roles` ( `NOMBREDELROL`, `ALTADECATALOGOS`, `BAJADECATALOGOS`, `MODIFICACIOnDECATALOGOS`, `ALTADEUSUARIOS`, `BAJADEUSUARIOS`, `MODIFICACIONDEUSUARIOS`, `ALTADEROL`, `BAJADEROL`, `MODIFICACIONDEROL`, `ALTADEVALORACIONINICIAL`, `MODIFICACIONREAPERTURAVALORACIONINICIAL`, `EDITARANTESDECIERREDELAVALORACIONINICIAL`, `BAJAVALORACIONINICIAL`, `IMPRESIONVALORACIONINICIAL`, `VISUALIZACIONVALORACIONINICIAL`, `ALTADEVALORACIONINTEGRAL`, `MODIFICACIONREAPERTURAVALORACIONINTEGRAL`, `EDITARANTESDECIERREDELAVALORACIONINTEGRAL`, `BAJAVALORACIONINTEGRAL`, `IMPRESIONVALORACIONINTEGRAL`, `VISUALIZACIONVALORACIONINTEGRAL`, `ALTADESEGUIMIENTO`, `MODIFICACIONDESEGUIMIENTO`, `EDITARDESEGUIMIENTO`, `BAJADESEGUIMIENTO`, `IMPRESIONDESEGUIMIENTO`, `VISUALIZACIONDESEGUIMIENTO`, `ALTADECIERRE`, `MODIFICACIONDECIERRE`, `EDICIONDECIERRE`, `BAJADECIERRE`, `IMPRESIONDECIERRE`, `VISUALIZACIONDECIERRE`, `ALTADENUNCIA`, `MODIFCACIONDENUNCIA`, `EDICIONDENUNCIA`, `BAJADENUNCIA`, `IMPRESIONDENUNCIA`, `VISUALIZACIONDENUNCIA`, `ALTAINVESTIGACION`, `MODIFICACIONINVESTIGACION`, `EDICIONINVESTIGACION`, `BAJAINVESTIGACION`, `IMPRESIONINVESTIGACION`, `VISUALIZACIONINVESTIGACION`, `ALTAEVIDENCIA`, `MODIFCACIONEVIDENCIA`, `EDICIONEVIDENCIA`, `BAJAEVIDENCIA`, `IMPRESIONEVIDENCIA`, `VISUALIZACIONEVIDENCIA`, `ALTADEARCHIVOS`, `MODIFICACIONARCHIVOS`, `IMPRESIONARCHIVOS`, `VISUALIZACIONARCHIVOS`, `ACTIVO`) VALUES
( 'ADMIN', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', 'SI', b'0'),
";

$sql2 = "INSERT INTO `usuarios` ( `nombre`, `email`, `password`, `rol`, `programa`, `fechaCreacion`, `activo`) VALUES
( 'ADMINISTRADOR', 'a@g.com', '12345', '1', 1, '2021-01-08', '1')";


if ($conn->query($sql) === TRUE) {
  echo "rol insertado successfully";
} else {
  echo "Error creating rol: " . $conn->error;
}

if ($conn->query($sql2) === TRUE) {
  echo "Usuario admin creadro";
} else {
  echo "Error creating usuario admina: " . $conn->error;
}

$conn->close();
?> 